---
# This file is a template.  Copy it to another location to use it.  Do not
# modify its content, the modifications would be lost when upgrading the
# project.
#

# Basic system configuration.
- hosts: all
  gather_facts: true
  tasks:
  - include_tasks: "tasks/set-facts-{{ ansible_os_family }}.yaml"
  - include_tasks: "tasks/basic-system-{{ ansible_os_family }}.yaml"
  - include_tasks: "tasks/advanced-utilities-{{ ansible_os_family }}.yaml"

# PostgreSQL.
- hosts: pg
  gather_facts: false
  tasks:
  - include_tasks: "tasks/install-PostgreSQL-{{ ansible_os_family }}.yaml"
  - include_tasks: "tasks/create-PostgreSQL-instance-{{ ansible_os_family }}.yaml"



