---
- name: Install useful utilities
  become: true
  script: >
    scripts/system/install_pkg_apt.sh \
      "atop" \
      "strace" \
      "lsof" \
      "sysstat" \
      "rsync" \
      "screen" \
      "tcpdump" \
      "wget" \
      "vim"

