---
- name: Add "epel" repository
  become: true
  script: scripts/system/add_repo_yum.sh -n "epel-release"
- name: Install useful utilities
  become: true
  script: >
    scripts/system/install_pkg_yum.sh \
      "atop" \
      "perf" \
      "strace" \
      "lsof" \
      "sysstat" \
      "rsync" \
      "screen" \
      "tcpdump" \
      "wget" \
      "vim"

