---
# FIXME should we allow to create multiple instances?
# FIXME custom PGDATA not supported yet
#- name: Create the PGDATA directory
#  become: true
#  script: >
#      scripts/system/create_dir.sh \
#        -P "{{ vars['postgresql']['pgdata'] }}" \
#        -o "postgres" \
#        -p "700"
#  when: vars['postgresql']['pgdata'] is defined
- name: Configure the instance
  become: true
  become_user: "postgres"
  # FIXME using "psql" from the script requires become method to change the
  # home directory, thus adding "-i" flag
  become_method: "sudo"
  become_flags: "-i"
  script: >
      scripts/postgres/change_setting.sh \
        "{{ item.key }}" \
        "{{ item.value }}"
  # Loop on all elements from "settings" dictionary.
  loop: "{{ vars['postgresql']['settings']|dict2items }}"
- name: Initialize hba file
  become: true
  become_user: "postgres"
  # FIXME using "psql" from the script requires become method to change the
  # home directory, thus adding "-i" flag
  become_method: "sudo"
  become_flags: "-i"
  script: scripts/postgres/build_hba.sh -i
- name: Add lines to hba file from host configuration
  become: true
  become_user: "postgres"
  # FIXME using "psql" from the script requires become method to change the
  # home directory, thus adding "-i" flag
  become_method: "sudo"
  become_flags: "-i"
  script: >
      scripts/postgres/build_hba.sh \
        -l "{{ hba_line }}"
  loop: "{{ vars['postgresql']['hba_lines'] }}"
  loop_control:
    loop_var: "hba_line"
- name: Restart the instance
  become: true
  script: >
      scripts/system/manage_service.sh \
        -s "postgresql@{{ vars['postgresql']['version'] }}-main" \
        -a "restart" \
        -i "{{ vars['init_system'] }}"


