---
# FIXME should we allow to install multiple versions?
- name: Add "pgdg" repository
  become: true
  script: >
    scripts/system/add_repo_yum.sh -n "{{ vars['postgresql']['repo_url'] }}"
- name: Install PostgreSQL
  become: true
  script: >
    scripts/system/install_pkg_yum.sh \
      "{{ vars['postgresql']['packages']|join(' ') }}"
# FIXME configure "postgres" user .bashrc ...
# - change prompt to show hostname, PGDATA, PGPORT, PGUSER
# - change default EDITOR to vim and PAGER to less
# - change .psqlrc (\timing, show null, ascii formating, etc.)
#

