# This file is a template.  Copy it to another location to use it.  Do not
# modify its content, the modifications would be lost when upgrading the
# project.
#

# Very basic Debian Jessie machine, no provisioning, no networking outside of
# the one automatically built by Vagrant.
[machines]
[machines.deb8basic]
box              = "debian/jessie64"
box_check_update = false
hostname         = "deb8basic"
memory           = 1024
cpus             = 1
# Synced folders.
[machines.deb8basic.sync_folders]
[machines.deb8basic.sync_folders._listitem_share]
host  = "share"
guest = "/share"

