# This file is a template.  Copy it to another location to use it.  Do not
# modify its content, the modifications would be lost when upgrading the
# project.
#

# Machines configuration.
[machines]
[machines.srv2]
hostname = "srv2"

# Network.
[machines.srv2.private_networks]
[machines.srv2.private_networks._listitem_122]
# Static IP address for the machine.
ip_private = "192.168.122.32"
resolvname = "srv2"

# Forwarded Port.
[machines.srv2.fw_ports]
[machines.srv2.fw_ports._listitem_pgport]
guest = 5432
host  = 55432

# PostgreSQL configuration.
[machines.srv2.postgresql]
hba_lines = [
# Replication specific lines.
#   TYPE  DATABASE        USER            ADDRESS             METHOD
  "host replication  repliuser  192.168.122.31/32                md5",
  "host replication  repliuser  192.168.122.32/32             reject",
  "host replication  repliuser  192.168.122.33/32                md5"
]
[machines.srv2.postgresql.replication]
primary_host = "srv1"

